repos:
-   repo: local
    hooks:
    - id: flake8
      name: flake8
      description: wemake-python-styleguide enforcement
      entry: flake8
      args: ["--config=setup.cfg"]
      language: python
      types: [python]
    - id: mypy
      name: mypy
      description: control var types
      entry: mypy
      args: [--ignore-missing-imports, --explicit-package-bases]
      language: python
      types: [python]
    - id: isort
      name: isort
      description: control var types
      entry: isort
      language: python
      types: [python]