version: '3.7'

services:

  elasticsearch:
    platform: linux/x86_64
    image: elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      #- elasticsearch.username=kibana
      #- elasticsearch.password=your-password
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  

volumes:
  elasticsearch-data:
    driver: local
  pg_data: