# Generated by Django 4.2.3 on 2023-07-25 14:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyrusForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('form_name', models.CharField(default='-empty-', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('service', models.ManyToManyField(to='admin_panel.service')),
            ],
        ),
        migrations.CreateModel(
            name='SystemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('start_support_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('end_support_time', models.DecimalField(decimal_places=2, default=24, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.service')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.system')),
            ],
            options={
                'verbose_name': 'Система-сервис',
                'verbose_name_plural': 'Система-сервис',
            },
        ),
        migrations.CreateModel(
            name='SystemServiceMainTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(default='no name', max_length=30)),
                ('plan_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pyrus_stage', models.IntegerField()),
                ('start_support_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('end_support_time', models.DecimalField(decimal_places=2, default=24, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.CreateModel(
            name='SystemServiceСompetenceTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(default='no name', max_length=30)),
                ('plan_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pyrus_stage', models.IntegerField()),
                ('start_support_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('end_support_time', models.DecimalField(decimal_places=2, default=24, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.CreateModel(
            name='TimeTableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_work', models.BooleanField()),
                ('week', models.IntegerField()),
                ('year', models.IntegerField()),
                ('qr', models.IntegerField()),
                ('month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-empty-', max_length=255)),
                ('description', models.CharField(default='-empty-', max_length=255)),
                ('timetabledate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.timetabledate')),
            ],
        ),
        migrations.CreateModel(
            name='SystemServicePyrusForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.pyrusforms')),
                ('system_service', models.ManyToManyField(blank=True, to='admin_panel.systemservice')),
            ],
        ),
        migrations.AddField(
            model_name='systemservice',
            name='system_service_competence_teams',
            field=models.ManyToManyField(blank=True, to='admin_panel.systemserviceсompetenceteams'),
        ),
        migrations.AddField(
            model_name='systemservice',
            name='system_service_main_teams',
            field=models.ManyToManyField(blank=True, to='admin_panel.systemservicemainteams'),
        ),
        migrations.CreateModel(
            name='SystemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
                ('system', models.ManyToManyField(to='admin_panel.system')),
            ],
        ),
    ]
