# Generated by Django 4.2.3 on 2023-07-21 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('service', models.ManyToManyField(to='admin_panel.service')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SystemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('start_support_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('end_support_time', models.DecimalField(decimal_places=2, default=24, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.service')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.system')),
            ],
        ),
        migrations.CreateModel(
            name='SystemServiceMainTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(default='no name', max_length=30)),
                ('plan_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pyrus_stage', models.IntegerField()),
                ('system_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.systemservice')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='system',
            field=models.ManyToManyField(to='admin_panel.systemalias'),
        ),
        migrations.AddField(
            model_name='system',
            name='system_service_main_teams',
            field=models.ManyToManyField(to='admin_panel.systemservicemainteams'),
        ),
    ]
