# Generated by Django 4.2.3 on 2023-07-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='system_service_main_teams',
        ),
    ]
