# Generated by Django 4.2.3 on 2023-09-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='methodprovidingservice',
            options={'verbose_name': 'Справочник способов предоставления услуги', 'verbose_name_plural': 'Справочник способов предоставления услуги'},
        ),
        migrations.AlterModelOptions(
            name='pyrusforms',
            options={'verbose_name': 'Справочник форм пайруса', 'verbose_name_plural': 'Справочник форм пайруса'},
        ),
        migrations.AlterModelOptions(
            name='pyrususers',
            options={'verbose_name': 'Справочник менеджеров', 'verbose_name_plural': 'Справочник менеджеров'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Справочник услуг', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'Справочник систем', 'verbose_name_plural': 'Системы'},
        ),
        migrations.AlterModelOptions(
            name='systemalias',
            options={'verbose_name': 'Справочник синонимов системы', 'verbose_name_plural': 'Синонимы систем'},
        ),
        migrations.AlterModelOptions(
            name='systemcategory',
            options={'verbose_name': 'Справочник категорий систем', 'verbose_name_plural': 'Категории систем'},
        ),
        migrations.AlterModelOptions(
            name='systemservice',
            options={'verbose_name': 'Услуги для системы', 'verbose_name_plural': 'Услуги для системы'},
        ),
        migrations.AlterModelOptions(
            name='systemservicemainteams',
            options={'verbose_name': 'Основные команды сопровождения для услуг', 'verbose_name_plural': 'Основные команды сопровождения для услуг'},
        ),
        migrations.AlterModelOptions(
            name='systemserviceсompetenceteams',
            options={'verbose_name': 'Команды компетенций для услуг', 'verbose_name_plural': 'Команды компетенций для услуг'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Справочник календарей', 'verbose_name_plural': 'Справочник календарей'},
        ),
        migrations.AlterModelOptions(
            name='timetabledate',
            options={'verbose_name': 'Дни в календаре', 'verbose_name_plural': 'Дни в календаре'},
        ),
        migrations.AddField(
            model_name='pyrusforms',
            name='system_service',
            field=models.ManyToManyField(blank=True, to='admin_panel.systemservice'),
        ),
        migrations.DeleteModel(
            name='SystemServicePyrusForms',
        ),
    ]
