# Generated by Django 4.2.3 on 2023-07-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_timetable_timetabledate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetabledate',
            name='month',
        ),
    ]
