# Generated by Django 4.2.3 on 2023-07-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_remove_system_system_service_main_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='system',
            new_name='alias_system',
        ),
    ]
