# Generated by Django 4.2.3 on 2023-09-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_methodprovidingservice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyrusforms',
            name='system_service',
        ),
        migrations.AddField(
            model_name='systemservice',
            name='forms',
            field=models.ManyToManyField(blank=True, to='admin_panel.pyrusforms'),
        ),
    ]
