# Generated by Django 4.2.3 on 2023-07-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_rename_system_system_alias_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='system_service_main_teams',
            field=models.ManyToManyField(to='admin_panel.systemservicemainteams'),
        ),
    ]
