# Generated by Django 4.2.3 on 2023-07-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_systemservice_system_service_main_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemservicemainteams',
            name='system_service',
        ),
    ]
