# Generated by Django 4.2.3 on 2023-07-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_systemservicemainteams_system_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='alias_system',
        ),
        migrations.AddField(
            model_name='systemalias',
            name='system',
            field=models.ManyToManyField(to='admin_panel.system'),
        ),
    ]
