# Generated by Django 4.2.3 on 2023-07-25 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_timetabledate_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservice',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.timetable'),
        ),
        migrations.AddField(
            model_name='timetabledate',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
