# Generated by Django 4.2.3 on 2023-07-21 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_system_alias_system_systemalias_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemServiceСompetenceTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(default='no name', max_length=30)),
                ('plan_time', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('pyrus_stage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='systemservice',
            name='system_service_main_teams',
            field=models.ManyToManyField(null=True, to='admin_panel.systemservicemainteams'),
        ),
        migrations.AddField(
            model_name='systemservice',
            name='system_service_competence_teams',
            field=models.ManyToManyField(null=True, to='admin_panel.systemserviceсompetenceteams'),
        ),
    ]
