# Generated by Django 4.2.3 on 2023-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_systemserviceсompetenceteams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemservice',
            name='system_service_competence_teams',
            field=models.ManyToManyField(blank=True, null=True, to='admin_panel.systemserviceсompetenceteams'),
        ),
        migrations.AlterField(
            model_name='systemservice',
            name='system_service_main_teams',
            field=models.ManyToManyField(blank=True, null=True, to='admin_panel.systemservicemainteams'),
        ),
    ]
