# Generated by Django 4.2.3 on 2023-07-22 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_pyrusforms_remove_systemservicepyrusforms_form_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemservicemainteams',
            name='end_support_time',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='systemservicemainteams',
            name='start_support_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='systemserviceсompetenceteams',
            name='end_support_time',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='systemserviceсompetenceteams',
            name='start_support_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
